services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis_network
    volumes:
      - redis_data:/db
    command:
      - --requirepass ${REDIS_PASSWORD}

  insight:
    image: redislabs/redisinsight:latest
    container_name: insight
    restart: always
    depends_on:
      - redis
    ports:
      - ${REDISINSIGHT_PORT}:5540
    networks:
      - redis_network
    volumes:
      - redisinsight_data:/data

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local